import { useEffect, useState } from "react";
import { BarChart3, Gauge, Lightbulb, Target } from "lucide-react";
import { useLanguage } from "@/lib/language";
import { AssessmentPanel } from "../components/assessment-panel";
import { HeroSection } from "../components/hero-section";
import { ModuleSelector } from "../components/module-selector";
import type { Module, Question } from "../components/types";

const tx = (de: string, en: string) => ({ de, en });
const makeQuestion = (context: [string, string], statement: [string, string], correct: number, explanation: [string, string]): Question => ({
  de: statement[0], en: statement[1], context: tx(...context), statement: tx(...statement), explanation: tx(...explanation),
  options: [tx("richtig", "true"), tx("unbestimmt", "undetermined"), tx("falsch", "false")], correct,
  hint: tx("Beurteile ausschließlich anhand der Informationen im Text.", "Use only the information provided in the text."),
});
const reasoningQuestions: Question[] = [
  makeQuestion(["Ein Hausbesitzer kauft eine von zwei privaten Windkraftanlagen, wenn sie die preisgünstigste Anlage ist, deren Leistung genügt. Anlage A genügt erst ab 1100 Windstunden und muss auf einem frei stehenden Mast montiert sein. Anlage B genügt ab 900 Windstunden, außer sie steht nicht auf einem frei stehenden Mast; dann braucht sie ebenfalls 1100 Windstunden.", "A homeowner buys the cheaper of two private wind turbines whose output is sufficient. Turbine A is sufficient from 1,100 windy hours and must be mounted on a free-standing mast. Turbine B is sufficient from 900 hours, unless it is not on a free-standing mast; then it also needs 1,100 hours."], ["Die Anlage kann nicht auf einem frei stehenden Mast montiert werden und es wird keine Anlage gekauft. Also gibt es weniger als 900 Windstunden pro Jahr.", "The turbine cannot be mounted on a free-standing mast and no turbine is bought. Therefore, there are fewer than 900 windy hours per year."], 1, ["Aus der fehlenden Montagemöglichkeit folgt nur, dass A nicht genügt. Über die Windstunden wissen wir nichts Eindeutiges.", "The mounting restriction only tells us that A is not sufficient. We cannot determine the number of windy hours."]),
  makeQuestion(["Ein Edelmetallhändler beobachtet zwei Wochen den Goldpreis. Er behält seine Vorräte, wenn der Preis um mindestens ein Prozent steigt. Steigt er nicht um wenigstens ein Prozent, verkauft er ein Kilo. Fällt der Preis, verkauft er ein weiteres Kilo und bei einem Rückgang von mindestens einem Prozent nochmals eines.", "A precious-metal dealer observes the gold price for two weeks. He keeps his stock if the price rises by at least one percent. If it does not rise by at least one percent, he sells one kilo. If the price falls, he sells another kilo, and one more if it falls by at least one percent."], ["Der Händler verkauft genau zwei Kilogramm. Also ist der Goldpreis um weniger als ein Prozent gefallen.", "The dealer sells exactly two kilograms. Therefore, the gold price fell by less than one percent."], 1, ["Zwei Kilo werden sowohl bei unverändertem Preis als auch bei einem Rückgang unter einem Prozent verkauft.", "Two kilos are sold both when the price is unchanged and when it falls by less than one percent."]),
  makeQuestion(["In einem Wohnheim gibt es möblierte und unmöblierte Zimmer, einige mit eigener Küche. Möblierte Zimmer kosten mindestens 250 Euro. Möblierte Zimmer mit eigener Küche kosten mindestens 300 Euro. Unmöblierte Zimmer mit Küche kosten weniger als 300, aber mindestens 220 Euro.", "A residence has furnished and unfurnished rooms, some with their own kitchen. Furnished rooms cost at least 250 euros. Furnished rooms with a kitchen cost at least 300 euros. Unfurnished rooms with a kitchen cost less than 300, but at least 220 euros."], ["Ein Zimmer kostet mehr als 250 Euro und hat keine Küche. Also ist es nicht möbliert.", "A room costs more than 250 euros and has no kitchen. Therefore, it is unfurnished."], 2, ["Ein Preis über 250 Euro kann auch zu einem möblierten Zimmer gehören.", "A price above 250 euros can also belong to a furnished room."]),
];
const modules: Module[] = [
  { id: "reasoning", title: tx("Angewandtes Schlussfolgern", "Applied reasoning"), desc: tx("Texte analysieren und logische Schlüsse ziehen.", "Analyse texts and draw logical conclusions."), icon: Target, questions: reasoningQuestions },
  { id: "diagram", title: tx("Diagrammanalyse", "Diagram analysis"), desc: tx("Kennzahlen, Anteile und Veränderungen vergleichen.", "Compare figures, proportions and changes."), icon: BarChart3, questions: reasoningQuestions },
  { id: "problem", title: tx("Problemlösefähigkeit", "Problem solving"), desc: tx("Muster und effiziente Lösungswege finden.", "Find patterns and efficient solutions."), icon: Lightbulb, questions: reasoningQuestions },
  { id: "speed", title: tx("Verarbeitungsgeschwindigkeit", "Processing speed"), desc: tx("Exakte Übereinstimmungen schnell finden.", "Find exact matches quickly."), icon: Gauge, questions: reasoningQuestions },
];
type Phase = "intro" | "instruction" | "examples" | "ready" | "test" | "done";
export function HomePage() {
  const { language } = useLanguage(); const de = language === "de";
  const [id, setId] = useState("reasoning"); const [phase, setPhase] = useState<Phase>("intro"); const [index, setIndex] = useState(0); const [choice, setChoice] = useState<number | null>(null); const [score, setScore] = useState(0); const [seconds, setSeconds] = useState(0);
  const [progress, setProgress] = useState<Record<string, number>>(() => JSON.parse(localStorage.getItem("assessment-progress") ?? "{}")); const active = modules.find((item) => item.id === id)!; const text = (v: { de: string; en: string }) => v[de ? "de" : "en"];
  useEffect(() => { if (phase !== "test") return; const timer = window.setInterval(() => setSeconds((s) => s + 1), 1000); return () => window.clearInterval(timer); }, [phase]);
  const select = (value: string) => { setId(value); setPhase("intro"); setIndex(0); setChoice(null); setScore(0); setSeconds(0); };
  const start = () => { setPhase("instruction"); setIndex(0); setChoice(null); };
  const answer = (value: number) => { if (choice !== null) return; setChoice(value); if (value === active.questions[index].correct) setScore((s) => s + 1); };
  const next = () => { if (phase === "instruction") return setPhase("examples"); if (phase === "examples") return index < 2 ? (setIndex(index + 1), setChoice(null)) : setPhase("ready"); if (phase === "ready") { setPhase("test"); setIndex(0); setChoice(null); setScore(0); setSeconds(0); return; } if (index < 2) return (setIndex(index + 1), setChoice(null)); const result = score + (choice === active.questions[index].correct ? 1 : 0); const updated = { ...progress, [id]: Math.max(progress[id] ?? 0, Math.round(result / 3 * 100)) }; setScore(result); setProgress(updated); localStorage.setItem("assessment-progress", JSON.stringify(updated)); setPhase("done"); };
  return <main className="min-h-[calc(100vh-73px)] bg-[#f7f8fc]"><HeroSection de={de} modules={modules} text={text} /><ModuleSelector de={de} modules={modules} selectedId={id} progress={progress} onSelect={select} text={text} /><AssessmentPanel de={de} active={active} phase={phase} questionIndex={index} choice={choice} seconds={seconds} score={score} onStart={start} onAnswer={answer} onNext={next} text={text} /></main>;
}
