import { useEffect, useState } from "react";
import { BarChart3, Gauge, Lightbulb, Target } from "lucide-react";
import { useLanguage } from "@/lib/language";
import { AssessmentPanel } from "../components/assessment-panel";
import { HeroSection } from "../components/hero-section";
import { ModuleSelector } from "../components/module-selector";
import type { Module, Question } from "../components/types";

const tx = (de: string, en: string) => ({ de, en });
const makeQuestion = (context: [string, string], statement: [string, string], correct: number, explanation: [string, string], visual?: Question["visual"]): Question => ({
  de: statement[0], en: statement[1], context: tx(...context), statement: tx(...statement), explanation: tx(...explanation),
  visual,
  options: [tx("richtig", "true"), tx("unbestimmt", "undetermined"), tx("falsch", "false")], correct,
  hint: tx("Beurteile ausschließlich anhand der Informationen im Text.", "Use only the information provided in the text."),
});
const reasoningQuestions: Question[] = [
  makeQuestion(["Ein Hausbesitzer kauft eine von zwei privaten Windkraftanlagen, wenn sie die preisgünstigste Anlage ist, deren Leistung genügt. Anlage A genügt erst ab 1100 Windstunden und muss auf einem frei stehenden Mast montiert sein. Anlage B genügt ab 900 Windstunden, außer sie steht nicht auf einem frei stehenden Mast; dann braucht sie ebenfalls 1100 Windstunden.", "A homeowner buys the cheaper of two private wind turbines whose output is sufficient. Turbine A is sufficient from 1,100 windy hours and must be mounted on a free-standing mast. Turbine B is sufficient from 900 hours, unless it is not on a free-standing mast; then it also needs 1,100 hours."], ["Die Anlage kann nicht auf einem frei stehenden Mast montiert werden und es wird keine Anlage gekauft. Also gibt es weniger als 900 Windstunden pro Jahr.", "The turbine cannot be mounted on a free-standing mast and no turbine is bought. Therefore, there are fewer than 900 windy hours per year."], 1, ["Aus der fehlenden Montagemöglichkeit folgt nur, dass A nicht genügt. Über die Windstunden wissen wir nichts Eindeutiges.", "The mounting restriction only tells us that A is not sufficient. We cannot determine the number of windy hours."]),
  makeQuestion(["Ein Edelmetallhändler beobachtet zwei Wochen den Goldpreis. Er behält seine Vorräte, wenn der Preis um mindestens ein Prozent steigt. Steigt er nicht um wenigstens ein Prozent, verkauft er ein Kilo. Fällt der Preis, verkauft er ein weiteres Kilo und bei einem Rückgang von mindestens einem Prozent nochmals eines.", "A precious-metal dealer observes the gold price for two weeks. He keeps his stock if the price rises by at least one percent. If it does not rise by at least one percent, he sells one kilo. If the price falls, he sells another kilo, and one more if it falls by at least one percent."], ["Der Händler verkauft genau zwei Kilogramm. Also ist der Goldpreis um weniger als ein Prozent gefallen.", "The dealer sells exactly two kilograms. Therefore, the gold price fell by less than one percent."], 1, ["Zwei Kilo werden sowohl bei unverändertem Preis als auch bei einem Rückgang unter einem Prozent verkauft.", "Two kilos are sold both when the price is unchanged and when it falls by less than one percent."]),
  makeQuestion(["In einem Wohnheim gibt es möblierte und unmöblierte Zimmer, einige mit eigener Küche. Möblierte Zimmer kosten mindestens 250 Euro. Möblierte Zimmer mit eigener Küche kosten mindestens 300 Euro. Unmöblierte Zimmer mit Küche kosten weniger als 300, aber mindestens 220 Euro.", "A residence has furnished and unfurnished rooms, some with their own kitchen. Furnished rooms cost at least 250 euros. Furnished rooms with a kitchen cost at least 300 euros. Unfurnished rooms with a kitchen cost less than 300, but at least 220 euros."], ["Ein Zimmer kostet mehr als 250 Euro und hat keine Küche. Also ist es nicht möbliert.", "A room costs more than 250 euros and has no kitchen. Therefore, it is unfurnished."], 2, ["Ein Preis über 250 Euro kann auch zu einem möblierten Zimmer gehören.", "A price above 250 euros can also belong to a furnished room."]),
];
const diagramExamples: Question[] = [
  makeQuestion(["Die Bevölkerung einer Stadt wurde jährlich nach der wahrgenommenen Lärmbelastung gefragt. Die Belastung konnte als stark, mittel oder gering eingestuft werden.", "The population of a city was surveyed annually about perceived noise pollution. The level could be rated as high, medium or low."], ["In dem Jahr, in dem sich der größte Anteil der Bevölkerung von Lärm belästigt fühlte, fühlte sich auch der größte Anteil stark durch Lärm belästigt.", "In the year in which the largest share of the population felt disturbed by noise, the largest share also felt highly disturbed by noise."], 2, ["2016 fühlte sich insgesamt der größte Anteil durch Lärm belastet. Der höchste Anteil starker Belastung wurde jedoch 2013 gemessen. Die Aussage ist falsch.", "The largest total share felt disturbed in 2016, but the highest share of severe disturbance was measured in 2013. The statement is false."], "noise"),
  makeQuestion(["Die Geschwindigkeit dreier Autos wurde in den ersten 240 Sekunden ihrer Fahrt gemessen.", "The speed of three cars was measured during the first 240 seconds of their journey."], ["Wenn die erreichten Geschwindigkeiten bis zum Ende der Fahrt konstant bleiben, wird Auto C als letztes seinen Zielort erreichen.", "If the speeds reached remain constant until the end of the journey, Car C will be the last to reach its destination."], 1, ["Die Entfernungen zu den jeweiligen Zielorten sind nicht angegeben. Daher lässt sich die Reihenfolge nicht bestimmen.", "The distances to the destinations are not provided, so the arrival order cannot be determined."], "cars"),
  makeQuestion(["Von 2009 bis 2016 wurden die Sonnenstunden im jeweiligen Winter und die Durchschnittstemperatur im darauffolgenden April erhoben.", "From 2009 to 2016, winter sunshine hours and the average temperature in the following April were recorded."], ["Auf den Winter mit der geringsten Anzahl an Sonnenstunden folgte der April mit der niedrigsten Durchschnittstemperatur.", "The winter with the fewest sunshine hours was followed by the April with the lowest average temperature."], 0, ["Der Winter 2015/2016 hatte die wenigsten Sonnenstunden; darauf folgte zugleich der kälteste April. Die Aussage ist richtig.", "Winter 2015/2016 had the fewest sunshine hours and was followed by the coldest April. The statement is true."], "weather"),
];
const diagramQuestions: Question[] = [
  makeQuestion(["In fünf Ländern wurde der jeweilige Stromverbrauch des Jahres 2007 mit dem des Jahres 2017 verglichen.", "Electricity consumption in five countries was compared between 2007 and 2017."], ["Land A hatte sowohl 2007 als auch 2017 den weltweit größten Stromverbrauch.", "Country A had the highest electricity consumption worldwide in both 2007 and 2017."], 1, ["Das Diagramm zeigt nur fünf Länder. Ein weltweiter Vergleich ist deshalb nicht möglich.", "The chart shows only five countries, so a worldwide comparison is not possible."], "energy"),
  makeQuestion(["Die Anzahl der jährlich verkauften Eintrittskarten wurde für drei Museen von 2013 bis 2017 erfasst.", "The number of tickets sold annually was recorded for three museums from 2013 to 2017."], ["Die Gesamtzahl der verkauften Eintrittskarten aller Museen war 2016 am höchsten.", "The total number of tickets sold by all museums was highest in 2016."], 2, ["Addiert man die drei Reihen, ist die Gesamtsumme 2014 höher als 2016. Die Aussage ist falsch.", "Adding the three series shows that the total for 2014 is higher than for 2016. The statement is false."], "museums"),
  makeQuestion(["Für fünf Standorte eines Unternehmens wurde der jeweilige Anteil am Jahresumsatz ermittelt.", "The share of annual revenue was determined for five company locations."], ["Standort C hat einen mehr als doppelt so hohen Anteil am Jahresumsatz wie Standort A.", "Location C has more than twice the share of annual revenue of location A."], 0, ["Standort C erreicht 31 %, Standort A 15 %. Das Doppelte von 15 % sind 30 %, daher ist die Aussage richtig.", "Location C accounts for 31% and Location A for 15%. Twice 15% is 30%, so the statement is true."], "revenue"),
];
const modules: Module[] = [
  { id: "reasoning", title: tx("Angewandtes Schlussfolgern", "Applied reasoning"), desc: tx("Texte analysieren und logische Schlüsse ziehen.", "Analyse texts and draw logical conclusions."), icon: Target, questions: reasoningQuestions },
  { id: "diagram", title: tx("Diagrammanalyse", "Diagram analysis"), desc: tx("Kennzahlen, Anteile und Veränderungen vergleichen.", "Compare figures, proportions and changes."), icon: BarChart3, questions: diagramQuestions, examples: diagramExamples, duration: 60 },
  { id: "problem", title: tx("Problemlösefähigkeit", "Problem solving"), desc: tx("Muster und effiziente Lösungswege finden.", "Find patterns and efficient solutions."), icon: Lightbulb, questions: reasoningQuestions },
  { id: "speed", title: tx("Verarbeitungsgeschwindigkeit", "Processing speed"), desc: tx("Exakte Übereinstimmungen schnell finden.", "Find exact matches quickly."), icon: Gauge, questions: reasoningQuestions },
];
type Phase = "intro" | "instruction" | "examples" | "ready" | "test" | "done";
export function HomePage() {
  const { language } = useLanguage(); const de = language === "de";
  const [id, setId] = useState("reasoning"); const [phase, setPhase] = useState<Phase>("intro"); const [index, setIndex] = useState(0); const [choice, setChoice] = useState<number | null>(null); const [score, setScore] = useState(0); const [seconds, setSeconds] = useState(0);
  const [progress, setProgress] = useState<Record<string, number>>(() => JSON.parse(localStorage.getItem("assessment-progress") ?? "{}")); const active = modules.find((item) => item.id === id)!; const text = (v: { de: string; en: string }) => v[de ? "de" : "en"];
  const select = (value: string) => { setId(value); setPhase("intro"); setIndex(0); setChoice(null); setScore(0); setSeconds(0); };
  const start = () => { setPhase("instruction"); setIndex(0); setChoice(null); };
  const answer = (value: number) => { if (choice !== null) return; setChoice(value); };
  const next = () => { if (phase === "instruction") return setPhase("examples"); if (phase === "examples") return index < 2 ? (setIndex(index + 1), setChoice(null)) : setPhase("ready"); if (phase === "ready") { setPhase("test"); setIndex(0); setChoice(null); setScore(0); setSeconds(0); return; } const result = score + (choice === active.questions[index].correct ? 1 : 0); if (index < 2) { setScore(result); setIndex(index + 1); setChoice(null); setSeconds(0); return; } const updated = { ...progress, [id]: Math.max(progress[id] ?? 0, Math.round(result / 3 * 100)) }; setScore(result); setProgress(updated); localStorage.setItem("assessment-progress", JSON.stringify(updated)); setPhase("done"); };
  useEffect(() => { if (phase !== "test") return; const timer = window.setInterval(() => setSeconds((s) => s + 1), 1000); return () => window.clearInterval(timer); }, [phase, index]);
  useEffect(() => { if (phase === "test" && seconds >= (active.duration ?? 90)) next(); }, [seconds, phase]);
  return <main className="min-h-[calc(100vh-73px)] bg-[#f7f8fc]"><HeroSection de={de} modules={modules} text={text} /><ModuleSelector de={de} modules={modules} selectedId={id} progress={progress} onSelect={select} text={text} /><AssessmentPanel de={de} active={active} phase={phase} questionIndex={index} choice={choice} seconds={seconds} score={score} onStart={start} onAnswer={answer} onNext={next} text={text} /></main>;
}
