import { ArrowRight, Check, Clock3, Info, Play, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { DiagramChart } from "./diagram-chart";
import { ProblemPuzzle } from "./problem-puzzle";
import { ProcessingSpeedTask } from "./processing-speed-task";
import type { Module } from "./types";

type Phase = "intro" | "instruction" | "examples" | "ready" | "test" | "done";
type Props = { de: boolean; active: Module; phase: Phase; questionIndex: number; choice: number | null; seconds: number; score: number; onStart: () => void; onAnswer: (value: number) => void; onNext: () => void; text: (value: { de: string; en: string }) => string };

export function AssessmentPanel({ de, active, phase, questionIndex, choice, seconds, score, onStart, onAnswer, onNext, text }: Props) {
  const example = phase === "examples";
  const current = (example ? active.examples ?? active.questions : active.questions)[questionIndex];
  const diagram = active.id === "diagram";
  const problem = active.id === "problem";
  const speed = active.id === "speed";
  const duration = active.duration ?? 90;
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  if (phase === "intro" && speed) return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="bg-white p-8 sm:p-14"><h2 className="text-2xl font-semibold">{text(active.title)}</h2><p className="mt-7 max-w-2xl text-base leading-8 text-slate-600">{de ? "Vergleiche Werte, die durch Symbole dargestellt werden, so schnell und genau wie möglich." : "Compare values represented by symbols as quickly and accurately as possible."}</p><Button size="lg" className="mt-12 gap-2" onClick={onStart}>{de ? "Weiter zur Instruktion" : "Continue to instruction"}<ArrowRight className="h-4 w-4" /></Button></Card></section>;
  if (phase === "instruction" && speed) return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="bg-white p-8 sm:p-14"><h2 className="text-2xl font-semibold">{de ? "So funktioniert die Aufgabe" : "How the task works"}</h2><p className="mt-6 max-w-2xl text-base leading-8 text-slate-600">{de ? "Jedes Symbol entspricht einer Zahl. Berechne die beiden grauen Felder und wähle den geforderten Wert. Die Symbol-Legende bleibt während der Aufgabe sichtbar." : "Each symbol represents a number. Calculate both grey fields and choose the requested value. The symbol legend remains visible during the task."}</p><ProcessingSpeedTask task={active.questions[0].speed!} selected={null} correct={active.questions[0].correct} onSelect={() => undefined} de={de} /><Button size="lg" className="mt-8 gap-2" onClick={onNext}>{de ? "Beispielaufgaben ansehen" : "See examples"}<ArrowRight className="h-4 w-4" /></Button></Card></section>;
  if (phase === "ready" && speed) return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="bg-white p-8 sm:p-14"><Info className="h-12 w-12 text-indigo-500" /><h2 className="mt-5 text-2xl font-semibold">{de ? "Bereit für das Modul?" : "Ready for the module?"}</h2><p className="mt-5 max-w-2xl text-base leading-8 text-slate-600">{de ? "Die Bearbeitungszeit ist auf 23 Sekunden begrenzt. Löse in dieser Zeit so viele Aufgaben wie möglich." : "The total processing time is limited to 23 seconds. Solve as many tasks as possible within this time."}</p><Button size="lg" className="mt-10 gap-2" onClick={onNext}><Play className="h-4 w-4" />{de ? "Modul starten" : "Start module"}</Button></Card></section>;
  if ((phase === "examples" || phase === "test") && speed) return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="bg-white p-7 sm:p-12"><div className="flex items-center justify-between"><span className="text-sm font-semibold">{de ? `Aufgabe ${questionIndex + 1}` : `Task ${questionIndex + 1}`}</span><span className="font-mono text-sm text-slate-500">{phase === "examples" ? (de ? "Übung" : "Practice") : time}</span></div><ProcessingSpeedTask task={current.speed!} selected={choice} correct={current.correct} onSelect={onAnswer} de={de} /><div className="mt-8 flex justify-end"><Button disabled={choice === null} onClick={onNext} className="gap-2">{phase === "examples" ? (questionIndex === (active.examples?.length ?? 4) - 1 ? (de ? "Weiter zu den Hinweisen" : "Continue to hints") : (de ? "Nächste Beispielaufgabe" : "Next example")) : (de ? "Nächste Aufgabe" : "Next task")}<ArrowRight className="h-4 w-4" /></Button></div></Card></section>;
  if (phase === "done" && speed) return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="bg-white text-center"><div className="p-12 sm:p-20"><Check className="mx-auto h-14 w-14 text-emerald-500" /><h2 className="mt-6 text-3xl font-semibold">{de ? "Geschafft!" : "Well done!"}</h2><p className="mt-4 text-slate-500">{de ? `Du hast ${score} Aufgaben richtig gelöst.` : `You answered ${score} tasks correctly.`}</p><Button className="mt-8 gap-2" onClick={onStart}><RotateCcw className="h-4 w-4" />{de ? "Noch einmal üben" : "Practice again"}</Button></div></Card></section>;
  const labels = de ? ["Einführung", "Instruktion", "Beispielaufgaben", "Hinweise & Beginn"] : ["Introduction", "Instruction", "Examples", "Hints & start"];

  if (phase === "done") return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="overflow-hidden bg-white text-center"><div className="p-12 sm:p-20"><Check className="mx-auto h-14 w-14 text-emerald-500" /><h2 className="mt-6 text-3xl font-semibold">{de ? "Geschafft!" : "Well done!"}</h2><p className="mt-4 text-slate-500">{de ? `Du hast ${score} von ${active.questions.length} Aufgaben richtig gelöst. Dein Ergebnis wurde gespeichert.` : `You answered ${score} of ${active.questions.length} tasks correctly. Your result was saved.`}</p><Button className="mt-8 gap-2" onClick={onStart}><RotateCcw className="h-4 w-4" />{de ? "Noch einmal üben" : "Practice again"}</Button></div><div className="bg-slate-800 p-7 text-white"><p className="text-lg font-semibold">{de ? "Nächstes Training" : "Next practice"}</p><p className="mt-1 text-sm text-slate-300">{de ? "Wähle einen weiteren Bereich aus, wenn du bereit bist." : "Choose another skill when you are ready."}</p></div></Card></section>;

  if (phase === "intro" || phase === "instruction" || phase === "ready") return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="overflow-hidden bg-white"><div className="grid grid-cols-4 border-b border-slate-100 text-center text-xs font-medium sm:text-sm">{labels.map((label, i) => <div className={`min-w-0 break-words px-2 py-4 ${((phase === "intro" && i === 0) || (phase === "instruction" && i === 1) || (phase === "ready" && i === 3)) ? "bg-slate-200 font-semibold text-slate-800" : "text-slate-400"}`} key={label}>{label}</div>)}</div><div className="min-h-[410px] p-8 sm:p-14">
    {phase === "intro" && <><h2 className="text-2xl font-semibold">{text(active.title)}</h2><p className="mt-7 max-w-2xl text-base leading-8 text-slate-600">{problem ? (de ? "In diesem Modul geht es darum, Regeln zu erkennen und diese korrekt anzuwenden." : "This module is about identifying rules and applying them correctly.") : diagram ? (de ? "In diesem Modul geht es darum, Diagramme zu analysieren und korrekte Schlussfolgerungen daraus zu ziehen." : "This module is about analysing charts and drawing the correct conclusions from them.") : (de ? "In diesem Modul geht es darum, Texte zu analysieren und die korrekten Schlussfolgerungen daraus zu ziehen." : "This module is about analysing texts and drawing the correct conclusions from them.")}</p><p className="mt-5 max-w-2xl text-base leading-8 text-slate-600">{de ? "Nutze die anschließende Übungsphase, um dich mit dem Prinzip der Aufgaben vertraut zu machen." : "Use the following practice phase to become familiar with the task principle."}</p><Button size="lg" className="mt-12 gap-2" onClick={onStart}>{de ? "Weiter zur Instruktion" : "Continue to instruction"}<ArrowRight className="h-4 w-4" /></Button></>}
    {phase === "instruction" && <><h2 className="text-2xl font-semibold">{de ? "So funktioniert die Aufgabe" : "How the task works"}</h2><p className="mt-7 max-w-2xl text-base leading-8 text-slate-600">{problem ? (de ? "Du siehst ein Raster aus 16 Kästchen. Ein Kästchen ist leer. Wähle aus sechs Möglichkeiten die Ergänzung, die das Raster logisch vervollständigt." : "You will see a grid of 16 tiles with one tile missing. Choose the option that logically completes the grid from six possible answers.") : diagram ? (de ? "Du siehst jeweils ein Diagramm mit einer kurzen Beschreibung und einer Aussage. Beurteile die Aussage ausschließlich anhand dieser Informationen." : "You will see a chart with a short description and a statement. Assess the statement using only this information.") : (de ? "Du siehst jeweils einen Text und eine dazugehörige Schlussfolgerung. Prüfe, ob diese logisch richtig, falsch oder unbestimmt ist." : "You will see a text and a related conclusion. Decide whether it is true, false or undetermined.")}</p>{problem ? <div className="mt-8 rounded-xl bg-slate-50 p-5 text-sm leading-7 text-slate-600"><p>{de ? "Die Regeln können zeilenweise, spaltenweise oder über das gesamte Raster gelten." : "Rules may apply by row, by column or across the entire grid."}</p><p className="mt-2">{de ? "Achte auf Anzahl, Position, Farbe, Größe und Kombination der Symbole." : "Pay attention to the number, position, colour, size and combination of symbols."}</p></div> : <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-emerald-50 p-4"><b>{de ? "richtig" : "true"}</b><p className="mt-1 text-sm text-slate-600">{de ? "Kann abgeleitet werden." : "Can be derived."}</p></div><div className="rounded-xl bg-amber-50 p-4"><b>{de ? "unbestimmt" : "undetermined"}</b><p className="mt-1 text-sm text-slate-600">{de ? "Informationen fehlen." : "Information is missing."}</p></div><div className="rounded-xl bg-rose-50 p-4"><b>{de ? "falsch" : "false"}</b><p className="mt-1 text-sm text-slate-600">{de ? "Widerspricht den Daten." : "Contradicts the data."}</p></div></div>}{diagram && <p className="mt-6 text-sm text-slate-500">{de ? "Mit dem Vergrößerungssymbol kannst du jedes Diagramm genauer ansehen." : "Use the enlarge icon to inspect any chart in detail."}</p>}<Button size="lg" className="mt-9 gap-2" onClick={onNext}>{de ? "Beispielaufgaben ansehen" : "See examples"}<ArrowRight className="h-4 w-4" /></Button></>}
    {phase === "ready" && <><Info className="h-12 w-12 text-indigo-500" /><h2 className="mt-5 text-2xl font-semibold">{de ? "Bereit für das Modul?" : "Ready for the module?"}</h2><p className="mt-5 max-w-2xl text-base leading-8 text-slate-600">{de ? `Für die folgenden 3 Aufgaben hast du jeweils ${duration} Sekunden Zeit. Bearbeitete Aufgaben können nicht wiederholt werden.` : `You have ${duration} seconds for each of the following 3 tasks. Completed tasks cannot be revisited.`}</p><Button size="lg" className="mt-10 gap-2" onClick={onNext}><Play className="h-4 w-4" />{de ? "Modul starten" : "Start module"}</Button></>}
  </div></Card></section>;

  return <section className="mx-auto max-w-4xl px-6 pb-20"><Card className="bg-white p-7 sm:p-12"><div className="flex items-center justify-between"><span className="text-sm font-semibold">{questionIndex + 1} / {active.questions.length}</span><span className="flex items-center gap-2 font-mono text-sm text-slate-500"><Clock3 className="h-4 w-4" />{example ? (de ? "Übung" : "Practice") : time}</span></div><div className={diagram || problem ? "mt-7 text-base leading-7 text-slate-700" : "mt-8 rounded-xl bg-slate-50 p-6 text-base leading-7 text-slate-700"}>{text(current.context!)}</div>{current.visual && <DiagramChart visual={current.visual} de={de} />}{current.puzzle && <ProblemPuzzle puzzle={current.puzzle} selected={choice} correct={current.correct} onSelect={onAnswer} de={de} />}{!current.puzzle && <><p className="mt-7 text-sm italic text-slate-500">{de ? "Beurteile die Aussage anhand der vorliegenden Informationen." : "Assess the statement based on the information provided."}</p><h3 className="mt-4 text-lg font-semibold leading-7">{text(current.statement!)}</h3><div className="mt-7 grid gap-3 sm:grid-cols-3">{current.options.map((option, value) => { const correct = choice !== null && value === current.correct; const wrong = choice === value && !correct; return <button key={value} onClick={() => onAnswer(value)} className={`rounded-lg border-2 px-4 py-3 font-semibold transition ${correct ? "border-emerald-400 bg-emerald-50 text-emerald-800" : wrong ? "border-rose-400 bg-rose-50 text-rose-800" : "border-slate-200 hover:border-indigo-400"}`}>{text(option)}{correct && <Check className="ml-2 inline h-4 w-4" />}{wrong && <X className="ml-2 inline h-4 w-4" />}</button> })}</div></>}{choice !== null && <div className="mt-7 rounded-xl border border-indigo-100 bg-indigo-50 p-5 text-sm leading-6 text-indigo-950"><b>{de ? "Erklärung" : "Explanation"}</b><p className="mt-2">{text(current.explanation!)}</p></div>}<div className="mt-9 flex justify-end"><Button disabled={choice === null} onClick={onNext} className="gap-2">{example ? (questionIndex === active.questions.length - 1 ? (de ? "Weiter zu den Hinweisen" : "Continue to hints") : (de ? "Nächste Beispielaufgabe" : "Next example")) : (questionIndex === active.questions.length - 1 ? (de ? "Beenden" : "Finish") : (de ? "Nächste Aufgabe" : "Next task"))}<ArrowRight className="h-4 w-4" /></Button></div></Card></section>;
}
