import { ArrowRight, Check, Clock3, Play, TimerReset, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { Module } from "./types";

type AssessmentPanelProps = { de: boolean; active: Module; running: boolean; questionIndex: number; choice: number | null; seconds: number; onStart: () => void; onAnswer: (value: number) => void; onNext: () => void; text: (value: { de: string; en: string }) => string };

export function AssessmentPanel({ de, active, running, questionIndex, choice, seconds, onStart, onAnswer, onNext, text }: AssessmentPanelProps) {
  const current = active.questions[questionIndex];
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <section className="mx-auto max-w-6xl px-6 pb-16"><Card className="border-slate-200 bg-white p-6 sm:p-8">
    {!running ? <><div className="flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">{de ? "Aktueller Bereich" : "Current focus"}</p><h2 className="mt-2 text-2xl font-semibold">{text(active.title)}</h2><p className="mt-2 text-sm text-slate-500">{de ? "3 Fragen · sofortiges Feedback" : "3 questions · instant feedback"}</p></div><TimerReset className="h-7 w-7 text-indigo-400" /></div><div className="my-6 grid gap-3 border-y border-slate-100 py-5 text-sm text-slate-600 sm:grid-cols-3"><span>✓ {de ? "Sofortige Prüfung" : "Instant checking"}</span><span>✓ {de ? "Erklärungen" : "Explanations"}</span><span>✓ {de ? "Fortschritt gespeichert" : "Progress saved"}</span></div><Button size="lg" className="gap-2" onClick={onStart}><Play className="h-4 w-4" />{de ? "Training starten" : "Start practice"}</Button></> : <div><div className="mb-7 flex justify-between"><div><p className="font-semibold text-indigo-600">{text(active.title)}</p><p className="mt-1 text-sm text-slate-500">{de ? "Frage" : "Question"} {questionIndex + 1} {de ? "von" : "of"} 3</p></div><span className="flex items-center gap-2 rounded-full bg-slate-100 px-3 py-2 font-mono text-sm"><Clock3 className="h-4 w-4" />{time}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${((questionIndex + (choice !== null ? 1 : 0)) / 3) * 100}%` }} /></div><h3 className="mt-8 text-xl font-semibold leading-8">{text(current)}</h3><div className="mt-6 grid gap-3">{current.options.map((option, value) => { const correct = choice !== null && value === current.correct; const wrong = choice === value && !correct; return <button key={option.en} onClick={() => onAnswer(value)} className={`flex justify-between rounded-xl border p-4 text-left text-sm ${correct ? "border-emerald-400 bg-emerald-50 text-emerald-800" : wrong ? "border-rose-400 bg-rose-50 text-rose-800" : "border-slate-200 hover:border-indigo-300"}`}><span><b className="mr-3">{String.fromCharCode(65 + value)}</b>{text(option)}</span>{correct && <Check className="h-4 w-4" />}{wrong && <X className="h-4 w-4" />}</button>; })}</div>{choice !== null && <div className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><b>{de ? "Hinweis:" : "Hint:"}</b> {text(current.hint)}</div>}<div className="mt-7 flex justify-end"><Button disabled={choice === null} onClick={onNext} className="gap-2">{questionIndex === 2 ? (de ? "Beenden" : "Finish") : (de ? "Nächste Frage" : "Next question")}<ArrowRight className="h-4 w-4" /></Button></div></div>}
  </Card></section>;
}
